Move to system_ext partition
* Fix build error on dynamic partition devices

Fixes:
error: packages/apps/Matlog/Android.bp:17:1: module "MatLog" variant "android_common": sdk_version:
sdk_version must have a value when the module is located at vendor or product(only if PRODUCT_ENFORC
E_PRODUCT_PARTITION_INTERFACE is set).

Signed-off-by: Jabiyeff <cebiyevanar@gmail.com>